version: '3.9'

services:
  mongo:
    image: mongo:latest
    container_name: mongo
    restart: unless-stopped
    ports:
      - "27017:27017"
    networks:
      - shared_network
    volumes:
      - mongo_data:/data/db
      - mongo_config:/data/configdb

  emqx:
    image: emqx:latest
    container_name: emqx
    restart: unless-stopped
    ports:
      - "1883:1883"
      - "8883:8883"
      - "8083:8083"
      - "18083:18083"
    networks:
      - shared_network
    volumes:
      - emqx_data:/opt/emqx/data
      - emqx_log:/opt/emqx/log
      - emqx_etc:/opt/emqx/etc

  redis:
    image: redis/redis-stack:latest
    container_name: redis
    restart: unless-stopped
    ports:
      - "6379:6379"
    networks:
      - shared_network
    volumes:
      - redis_data:/data

  meilisearch:
    image: getmeili/meilisearch:latest
    container_name: meilisearch
    restart: unless-stopped
    environment:
      MEILI_ENV: production
      MEILI_NO_ANALYTICS: "true"
      MEILI_MASTER_KEY: supersecuremasterkey123
      MEILI_DB_PATH: /meili_data
      MEILI_HTTP_ADDR: 0.0.0.0:7700
    ports:
      - "7700:7700"
    networks:
      - shared_network
    volumes:
      - meili_data:/meili_data

  # 🔹 External Meilisearch UI
  meilisearch-ui:
    image: riccoxie/meilisearch-ui:latest
    container_name: meilisearch-ui
    restart: on-failure:5
    ports:
      - "24900:24900"
    environment:
      MEILI_HTTP_ADDR: http://meilisearch:7700
      MEILI_MASTER_KEY: supersecuremasterkey123
    depends_on:
      - meilisearch
    networks:
      - shared_network

networks:
  shared_network:

volumes:
  mongo_data:
  mongo_config:
  redis_data:
  meili_data:
  emqx_data:
  emqx_log:
  emqx_etc:
